language: php

php:
  - 7.0

sudo: false

cache:
  directories:
    - .phpunit
    - $HOME/.composer/cache/files

# we could implement a matrix later

script: ./bin/run.sh

notifications:
  irc: "irc.freenode.org#symfony-cmf"
