language: php

sudo: false

env:
    - TEST_PACKAGE="symfony-cmf/core-bundle" TEST_VERSION="^2.0"
    - TEST_PACKAGE="symfony-cmf/content-bundle" TEST_VERSION="^2.0"
    - TEST_PACKAGE="symfony-cmf/tree-browser-bundle" TEST_VERSION="^2.0"
    - TEST_PACKAGE="symfony-cmf/routing-auto-bundle" TEST_VERSION="^2.0"
    - TEST_PACKAGE="symfony-cmf/routing-bundle" TEST_VERSION="^2.0"
    - TEST_PACKAGE="symfony-cmf/seo-bundle" TEST_VERSION="^2.0"
    - TEST_PACKAGE="symfony-cmf/menu-bundle" TEST_VERSION="^2.1"
    - TEST_PACKAGE="symfony-cmf/resource-rest-bundle" TEST_VERSION="^1.0"
    - TEST_PACKAGE="symfony-cmf/resource-bundle" TEST_VERSION="^1.0"
    - TEST_PACKAGE="symfony-cmf/sonata-phpcr-admin-integration-bundle" TEST_VERSION="^1.0"
    - TEST_PACKAGE="symfony-cmf/core-bundle" TEST_VERSION="dev-master"
    - TEST_PACKAGE="symfony-cmf/content-bundle" TEST_VERSION="dev-master"
    - TEST_PACKAGE="symfony-cmf/tree-browser-bundle" TEST_VERSION="dev-master"
    - TEST_PACKAGE="symfony-cmf/routing-auto-bundle" TEST_VERSION="dev-master"
    - TEST_PACKAGE="symfony-cmf/routing-bundle" TEST_VERSION="dev-master"
    - TEST_PACKAGE="symfony-cmf/seo-bundle" TEST_VERSION="dev-master"
    - TEST_PACKAGE="symfony-cmf/menu-bundle" TEST_VERSION="dev-master"
    - TEST_PACKAGE="symfony-cmf/resource-rest-bundle" TEST_VERSION="dev-master"
    - TEST_PACKAGE="symfony-cmf/resource-bundle" TEST_VERSION="dev-master"
    - TEST_PACKAGE="symfony-cmf/sonata-phpcr-admin-integration-bundle" TEST_VERSION="dev-master"
    - TEST_PACKAGE="doctrine/phpcr-bundle" TEST_VERSION="^1.4"
    - TEST_PACKAGE="doctrine/phpcr-bundle" TEST_VERSION="dev-master"

cache:
  directories:
    - .phpunit
    - $HOME/.composer/cache/files

script: ./bin/install.sh -p${TEST_PACKAGE} -v${TEST_VERSION}

notifications:
  irc: "irc.freenode.org#symfony-cmf"
