language: php

php:
  - 7.0

sudo: false

matrix:
    include:
        - env: TEST_PACKAGE="symfony-cmf/core-bundle"
          env: TEST_VERSION="^2.0"
        - env: TEST_PACKAGE="symfony-cmf/core-bundle"
          env: TEST_VERSION="^2.0"
        - env: TEST_PACKAGE="symfony-cmf/content-bundle"
          env: TEST_VERSION="^2.0"
        - env: TEST_PACKAGE="symfony-cmf/tree-browser-bundle"
          env: TEST_VERSION="^2.0"
        - env: TEST_PACKAGE="symfony-cmf/routing-auto-bundle"
          env: TEST_VERSION="^2.0"
        - env: TEST_PACKAGE="symfony-cmf/routing-bundle"
          env: TEST_VERSION="^2.0"
        - env: TEST_PACKAGE="symfony-cmf/seo-bundle"
          env: TEST_VERSION="^2.0"
        - env: TEST_PACKAGE="symfony-cmf/menu-bundle"
          env: TEST_VERSION="^2.1"
        - env: TEST_PACKAGE="symfony-cmf/resource-rest-bundle"
          env: TEST_VERSION="^1.0"
        - env: TEST_PACKAGE="symfony-cmf/resource-bundle"
          env: TEST_VERSION="^1.0"
        - env: TEST_PACKAGE="symfony-cmf/sonata-phpcr-admin-integration-bundle"
          env: TEST_VERSION="^1.0"

cache:
  directories:
    - .phpunit
    - $HOME/.composer/cache/files

script: ./bin/install.sh -p${TEST_PACKAGE} -v${TEST_VERSION}

notifications:
  irc: "irc.freenode.org#symfony-cmf"
